FROM php:8.3.9-apache

# シェルの設定
ENV SHELL /bin/bash

# compose.ymlから引数を受け取る
ARG UID=1000
ARG GID=1000

# パッケージリストの更新とパッケージのアップグレード
RUN apt-get update && \
    apt-get install -y \
    zip \
    unzip \
    git \
    curl \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    zlib1g-dev

# PHPの拡張機能をインストール
RUN docker-php-ext-install pdo pdo_mysql gd

# GDの設定（JPGとPNG対応）
RUN docker-php-ext-configure gd --with-jpeg --with-freetype

# Composerのインストール
COPY --from=composer /usr/bin/composer /usr/bin/composer

# mhsendmailのインストール
RUN curl -sSL https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 -o mhsendmail && \
    chmod +x mhsendmail && \
    mv mhsendmail /usr/local/bin/mhsendmail && \
    echo 'sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"' > /usr/local/etc/php/conf.d/sendmail.ini

# Apacheの設定
RUN a2enmod rewrite

# www-dataのUIDとGIDを設定
RUN groupmod -g ${GID} www-data && \
    usermod -u ${UID} www-data

# 作業ディレクトリをプロジェクトルートに設定
WORKDIR /var/www/html

# フォルダの権限を設定
RUN chmod -R 755 /var/www && \
    chown -R www-data:www-data /var/www

# www-dataに切り替え
USER www-data
